services:
  postgresql:
    build: ./postgresql
  redis:
    build: ./redis

  airflow:
    build: ./airflow
    ports:
      - '8080:8080'
    volumes:
      - ./scheduler/dags:/opt/bitnami/airflow/dags

  scheduler:
    build: ./scheduler
    volumes:
      - ./scheduler/dags:/opt/bitnami/airflow/dags 

  worker:
    build: ./worker
    volumes:
      - ./scheduler/dags:/opt/bitnami/airflow/dags
